specVersion: 1.0.0
name: osmosis-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-cosmos'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Cosmos
  (Osmosis) based SubQuery project
repository: 'https://github.com/subquery/cosmos-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: osmo-test-4
  endpoint: 'https://osmosis-testnet-archive.allthatnode.com:26657'
    # dictionary: 'https://api.subquery.network/sq/subquery/cosmos-osmosis-dictionary'
  chainTypes:
    cosmos.slashing.v1beta1:
      file: ./proto/cosmos/slashing/v1beta1/tx.proto
      messages:
        - MsgUnjail
    cosmos.gov.v1beta1:
      file: ./proto/cosmos/gov/v1beta1/tx.proto
      messages:
        - MsgVoteWeighted
    cosmos.gov.v1beta1.gov:
      file: ./proto/cosmos/gov/v1beta1/gov.proto
      messages:
        - WeightedVoteOption
    cosmos.base.v1beta1:
      file: ./proto/cosmos/cosmos.base.v1beta1.coin.proto
      messages:
        - Coin
    osmosis.gamm.v1beta1:
      file: ./proto/cosmos/osmosis/gamm/v1beta1/tx.proto
      messages:
        - MsgJoinPool
        - MsgSwapExactAmountIn
dataSources:
  - kind: cosmos/Runtime
    startBlock: 3215230
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: execute
            messageFilter:
              type: /cosmwasm.wasm.v1.MsgExecuteContract
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
